<script setup lang="ts">
import { motion, useReducedMotion } from "motion-v";

import { NBadge, NButton, NCard } from "../components/nagi";
import { componentGroups, ownedComponentCount, verifiedDefinitions } from "../data/components";

const reduceMotion = useReducedMotion();
const sourceColumns = [
  [componentGroups[0], componentGroups[3], componentGroups[2]],
  [componentGroups[1], componentGroups[4], componentGroups[5]],
] as const;
</script>

<template>
  <main class="source-view">
    <motion.header
      class="page-heading"
      :initial="reduceMotion ? undefined : { opacity: 0, y: 12 }"
      :animate="{ opacity: 1, y: 0 }"
      :transition="{ duration: reduceMotion ? 0 : 0.45 }"
    >
      <div class="heading-copy">
        <p class="eyebrow">Source ownership</p>
        <h1>The whole system is here.</h1>
        <p class="lede">
          Every canonical Vue component was copied by the Nagi UI ownership command. Open any file,
          change the markup, and keep its behavior contract visible.
        </p>
      </div>
      <a
        class="github-link"
        href="https://github.com/nagi-labs/nagi-ui-deep-sea/tree/main/src/components/nagi"
        target="_blank"
        rel="noreferrer"
      >
        Browse source ↗
      </a>
    </motion.header>

    <section
      class="ownership-summary"
      aria-label="Ownership summary"
    >
      <article>
        <strong>{{ ownedComponentCount }}</strong>
        <span>owned components</span>
      </article>
      <article>
        <strong>80</strong>
        <span>visible source files</span>
      </article>
      <article>
        <strong>{{ verifiedDefinitions.size }}</strong>
        <span>verified Definitions</span>
      </article>
    </section>

    <n-card
      class="ownership-card"
      title="What ownership means"
      description="Package behavior remains reusable; visible Vue structure belongs to this repository."
    >
      <div class="ownership-path">
        <code>src/components/nagi/</code>
        <span>← generated by</span>
        <code>vp exec nagi-ui own …</code>
      </div>
      <template #footer>
        <div class="axis-example">
          <span>Deep Sea styles the owned Button through component-local CSS axes.</span>
          <n-button class="axis-button">Bioluminescent action</n-button>
        </div>
      </template>
    </n-card>

    <section class="source-groups">
      <div
        v-for="(column, columnIndex) in sourceColumns"
        :key="columnIndex"
        class="source-column"
      >
        <motion.section
          v-for="(group, groupIndex) in column"
          :key="group.name"
          class="source-group"
          :initial="reduceMotion ? undefined : { opacity: 0, y: 12 }"
          :animate="{ opacity: 1, y: 0 }"
          :transition="{
            duration: reduceMotion ? 0 : 0.35,
            delay: reduceMotion ? 0 : (columnIndex * 3 + groupIndex) * 0.04,
          }"
        >
          <header>
            <h2>{{ group.name }}</h2>
            <span>{{ group.components.length }}</span>
          </header>
          <ul>
            <li
              v-for="component in group.components"
              :key="component"
            >
              <code>{{ component }}.vue</code>
              <n-badge
                v-if="verifiedDefinitions.has(component)"
                label="Definition verified"
                tone="success"
              />
              <n-badge
                v-else
                label="Definition WIP"
                tone="neutral"
              />
            </li>
          </ul>
        </motion.section>
      </div>
    </section>
  </main>
</template>
