<script setup lang="ts">
import { NBadge, NButton, NCard } from "../components/nagi";
import {
  componentGroups,
  ownedComponentCount,
  ownedSourceFileCount,
  verifiedDefinitions,
} from "../data/components";

const sourceColumns = [
  [componentGroups[0], componentGroups[2], componentGroups[4]],
  [componentGroups[1], componentGroups[3]],
] as const;
</script>

<template>
  <main class="deep-sea-component-source-view">
    <header class="header -page">
      <div class="unit -heading">
        <p class="p -eyebrow">Source ownership</p>
        <h1 class="title">Owned component source</h1>
        <p class="p -lede">
          Every component shown here is used by Deep Sea. Its Vue template, behavior wiring, styles,
          and available Definition can be reviewed beside the interface it produces.
        </p>
      </div>
      <a
        class="link -github"
        href="https://github.com/nagi-labs/nagi-ui-deep-sea/tree/main/src/components/nagi"
        target="_blank"
        rel="noreferrer"
      >
        Browse source ↗
      </a>
    </header>

    <section
      class="section -counts"
      aria-label="Ownership summary"
    >
      <article class="article">
        <strong class="strong">{{ ownedComponentCount }}</strong>
        <span class="text">owned components</span>
      </article>
      <article class="article">
        <strong class="strong">{{ ownedSourceFileCount }}</strong>
        <span class="text">owned source files</span>
      </article>
      <article class="article">
        <strong class="strong">{{ verifiedDefinitions.size }}</strong>
        <span class="text">verified Definitions</span>
      </article>
    </section>

    <n-card
      class="n-card -ownership"
      title="Ownership model"
      description="The installed package supplies shared behavior; the visible Vue structure belongs to this repository."
    >
      <div class="n-card-content">
        <div class="unit -path">
          <code class="code">src/components/nagi/</code>
          <span class="text">← generated by</span>
          <code class="code">vp exec nagi-ui own …</code>
        </div>
      </div>
      <template #footer>
        <div class="n-card-footer">
          <div class="unit -axis">
            <span class="text">
              Deep Sea styles the owned Button through component-local CSS axes.
            </span>
            <n-button class="n-button">Styled action</n-button>
          </div>
        </div>
      </template>
    </n-card>

    <section class="section -sources">
      <div
        v-for="(column, columnIndex) in sourceColumns"
        :key="columnIndex"
        class="unit -column"
      >
        <section
          v-for="group in column"
          :key="group.name"
          class="section -group"
        >
          <header class="header">
            <h2 class="title">{{ group.name }}</h2>
            <span class="text">{{ group.components.length }}</span>
          </header>
          <ul class="list">
            <li
              v-for="component in group.components"
              :key="component"
              class="item"
            >
              <code class="code">{{ component }}.vue</code>
              <n-badge
                v-if="verifiedDefinitions.has(component)"
                label="Definition verified"
                tone="success"
              />
              <n-badge
                v-else
                label="Definition WIP"
                tone="neutral"
              />
            </li>
          </ul>
        </section>
      </div>
    </section>
  </main>
</template>

<style scoped>
.deep-sea-component-source-view {
  display: grid;
  gap: var(--n-space-8);
  inline-size: min(100%, 82rem);
  padding: var(--n-space-8);

  > .header.-page {
    display: flex;
    gap: var(--n-space-8);
    align-items: end;
    justify-content: space-between;
    min-block-size: 4.75rem;

    > .unit.-heading {
      max-inline-size: 38rem;

      > .p.-eyebrow,
      > .p.-lede {
        color: var(--nagi-color-text-muted);
        font-size: var(--n-font-size-2);
      }
    }

    > .link.-github {
      flex: 0 0 auto;
      padding: var(--n-space-3) var(--n-space-5);
      border: var(--n-border-width-1) solid var(--nagi-color-border-muted);
      border-radius: var(--n-radius-2);
      color: var(--nagi-color-text);
      font-size: var(--n-font-size-2);
      font-weight: 600;
      text-decoration: none;
    }
  }

  > .section.-counts {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: var(--n-space-5);

    > .article {
      display: grid;
      gap: var(--n-space-1);
      padding: var(--n-space-7) var(--n-space-8);
      border: var(--n-border-width-1) solid var(--nagi-color-border-muted);
      border-radius: var(--n-radius-3);
      background: var(--nagi-color-surface);
    }
  }

  > .n-card.-ownership {
    border-color: var(--nagi-color-border-muted);
    border-radius: var(--n-radius-3);
    background: var(--nagi-color-surface);
    box-shadow: none;
  }

  > .section.-sources {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: var(--n-space-5);

    > .unit.-column {
      display: grid;
      gap: var(--n-space-5);
      align-content: start;

      > .section.-group {
        overflow: hidden;
        border: var(--n-border-width-1) solid var(--nagi-color-border-muted);
        border-radius: var(--n-radius-3);
        background: var(--nagi-color-surface);

        > .header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: var(--n-space-5) var(--n-space-7);
          border-block-end: var(--n-border-width-1) solid var(--nagi-color-border-muted);
        }

        > .list {
          margin: 0;
          padding: 0;
          list-style: none;

          > .item {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: var(--n-space-5) var(--n-space-7);
            border-block-end: var(--n-border-width-1) solid var(--nagi-color-border-muted);
          }
        }
      }
    }
  }
}

@media (max-width: 44rem) {
  .deep-sea-component-source-view {
    padding: var(--n-space-8);

    > .header.-page {
      align-items: start;
      flex-direction: column;
    }

    > .section.-counts,
    > .section.-sources {
      grid-template-columns: 1fr;
    }
  }
}
</style>
